// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";
import { Clock } from "../../../v1/Clock";
import { TransactionWithReceipt } from "../../../../starknet/type/v1/TransactionWithReceipt";

export class Transactions {
  static encode(message: Transactions, writer: Writer): void {
    const clock = message.clock;
    if (clock !== null) {
      writer.uint32(10);
      writer.fork();
      Clock.encode(clock, writer);
      writer.ldelim();
    }

    const transactionsWithReceipt = message.transactionsWithReceipt;
    for (let i: i32 = 0; i < transactionsWithReceipt.length; ++i) {
      writer.uint32(18);
      writer.fork();
      TransactionWithReceipt.encode(transactionsWithReceipt[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): Transactions {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Transactions();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.clock = Clock.decode(reader, reader.uint32());
          break;

        case 2:
          message.transactionsWithReceipt.push(
            TransactionWithReceipt.decode(reader, reader.uint32())
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  clock: Clock | null;
  transactionsWithReceipt: Array<TransactionWithReceipt>;

  constructor(
    clock: Clock | null = null,
    transactionsWithReceipt: Array<TransactionWithReceipt> = []
  ) {
    this.clock = clock;
    this.transactionsWithReceipt = transactionsWithReceipt;
  }
}
