// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";

export class ActualFee {
  static encode(message: ActualFee, writer: Writer): void {
    writer.uint32(10);
    writer.bytes(message.amount);

    writer.uint32(18);
    writer.string(message.unit);
  }

  static decode(reader: Reader, length: i32): ActualFee {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ActualFee();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.amount = reader.bytes();
          break;

        case 2:
          message.unit = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  amount: Uint8Array;
  unit: string;

  constructor(amount: Uint8Array = new Uint8Array(0), unit: string = "") {
    this.amount = amount;
    this.unit = unit;
  }
}
