// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";

export class DataAvailability {
  static encode(message: DataAvailability, writer: Writer): void {
    writer.uint32(8);
    writer.uint64(message.l1Gas);

    writer.uint32(16);
    writer.uint64(message.l1DataGas);
  }

  static decode(reader: Reader, length: i32): DataAvailability {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new DataAvailability();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.l1Gas = reader.uint64();
          break;

        case 2:
          message.l1DataGas = reader.uint64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  l1Gas: u64;
  l1DataGas: u64;

  constructor(l1Gas: u64 = 0, l1DataGas: u64 = 0) {
    this.l1Gas = l1Gas;
    this.l1DataGas = l1DataGas;
  }
}
