// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";

export class DeclareTransactionV1 {
  static encode(message: DeclareTransactionV1, writer: Writer): void {
    writer.uint32(18);
    writer.bytes(message.senderAddress);

    writer.uint32(26);
    writer.bytes(message.maxFee);

    writer.uint32(34);
    writer.string(message.version);

    const signature = message.signature;
    if (signature.length !== 0) {
      for (let i: i32 = 0; i < signature.length; ++i) {
        writer.uint32(42);
        writer.bytes(signature[i]);
      }
    }

    writer.uint32(50);
    writer.bytes(message.nonce);

    writer.uint32(58);
    writer.bytes(message.classHash);
  }

  static decode(reader: Reader, length: i32): DeclareTransactionV1 {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new DeclareTransactionV1();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2:
          message.senderAddress = reader.bytes();
          break;

        case 3:
          message.maxFee = reader.bytes();
          break;

        case 4:
          message.version = reader.string();
          break;

        case 5:
          message.signature.push(reader.bytes());
          break;

        case 6:
          message.nonce = reader.bytes();
          break;

        case 7:
          message.classHash = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  senderAddress: Uint8Array;
  maxFee: Uint8Array;
  version: string;
  signature: Array<Uint8Array>;
  nonce: Uint8Array;
  classHash: Uint8Array;

  constructor(
    senderAddress: Uint8Array = new Uint8Array(0),
    maxFee: Uint8Array = new Uint8Array(0),
    version: string = "",
    signature: Array<Uint8Array> = [],
    nonce: Uint8Array = new Uint8Array(0),
    classHash: Uint8Array = new Uint8Array(0)
  ) {
    this.senderAddress = senderAddress;
    this.maxFee = maxFee;
    this.version = version;
    this.signature = signature;
    this.nonce = nonce;
    this.classHash = classHash;
  }
}
