// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";
import { ResourceBounds } from "./ResourceBounds";
import { FEE_DATA_AVAILABILITY_MODE } from "./FEE_DATA_AVAILABILITY_MODE";

export class DeclareTransactionV3 {
  static encode(message: DeclareTransactionV3, writer: Writer): void {
    writer.uint32(18);
    writer.bytes(message.senderAddress);

    writer.uint32(26);
    writer.bytes(message.compiledClassHash);

    writer.uint32(34);
    writer.string(message.version);

    const signature = message.signature;
    if (signature.length !== 0) {
      for (let i: i32 = 0; i < signature.length; ++i) {
        writer.uint32(42);
        writer.bytes(signature[i]);
      }
    }

    writer.uint32(50);
    writer.bytes(message.nonce);

    writer.uint32(58);
    writer.bytes(message.classHash);

    const resourceBounds = message.resourceBounds;
    if (resourceBounds !== null) {
      writer.uint32(66);
      writer.fork();
      ResourceBounds.encode(resourceBounds, writer);
      writer.ldelim();
    }

    writer.uint32(74);
    writer.bytes(message.tip);

    const paymasterData = message.paymasterData;
    if (paymasterData.length !== 0) {
      for (let i: i32 = 0; i < paymasterData.length; ++i) {
        writer.uint32(82);
        writer.bytes(paymasterData[i]);
      }
    }

    const accountDeploymentData = message.accountDeploymentData;
    if (accountDeploymentData.length !== 0) {
      for (let i: i32 = 0; i < accountDeploymentData.length; ++i) {
        writer.uint32(90);
        writer.bytes(accountDeploymentData[i]);
      }
    }

    writer.uint32(96);
    writer.int32(message.nonceDataAvailabilityMode);

    writer.uint32(104);
    writer.int32(message.feeDataAvailabilityMode);
  }

  static decode(reader: Reader, length: i32): DeclareTransactionV3 {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new DeclareTransactionV3();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2:
          message.senderAddress = reader.bytes();
          break;

        case 3:
          message.compiledClassHash = reader.bytes();
          break;

        case 4:
          message.version = reader.string();
          break;

        case 5:
          message.signature.push(reader.bytes());
          break;

        case 6:
          message.nonce = reader.bytes();
          break;

        case 7:
          message.classHash = reader.bytes();
          break;

        case 8:
          message.resourceBounds = ResourceBounds.decode(
            reader,
            reader.uint32()
          );
          break;

        case 9:
          message.tip = reader.bytes();
          break;

        case 10:
          message.paymasterData.push(reader.bytes());
          break;

        case 11:
          message.accountDeploymentData.push(reader.bytes());
          break;

        case 12:
          message.nonceDataAvailabilityMode = reader.int32();
          break;

        case 13:
          message.feeDataAvailabilityMode = reader.int32();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  senderAddress: Uint8Array;
  compiledClassHash: Uint8Array;
  version: string;
  signature: Array<Uint8Array>;
  nonce: Uint8Array;
  classHash: Uint8Array;
  resourceBounds: ResourceBounds | null;
  tip: Uint8Array;
  paymasterData: Array<Uint8Array>;
  accountDeploymentData: Array<Uint8Array>;
  nonceDataAvailabilityMode: FEE_DATA_AVAILABILITY_MODE;
  feeDataAvailabilityMode: FEE_DATA_AVAILABILITY_MODE;

  constructor(
    senderAddress: Uint8Array = new Uint8Array(0),
    compiledClassHash: Uint8Array = new Uint8Array(0),
    version: string = "",
    signature: Array<Uint8Array> = [],
    nonce: Uint8Array = new Uint8Array(0),
    classHash: Uint8Array = new Uint8Array(0),
    resourceBounds: ResourceBounds | null = null,
    tip: Uint8Array = new Uint8Array(0),
    paymasterData: Array<Uint8Array> = [],
    accountDeploymentData: Array<Uint8Array> = [],
    nonceDataAvailabilityMode: FEE_DATA_AVAILABILITY_MODE = 0,
    feeDataAvailabilityMode: FEE_DATA_AVAILABILITY_MODE = 0
  ) {
    this.senderAddress = senderAddress;
    this.compiledClassHash = compiledClassHash;
    this.version = version;
    this.signature = signature;
    this.nonce = nonce;
    this.classHash = classHash;
    this.resourceBounds = resourceBounds;
    this.tip = tip;
    this.paymasterData = paymasterData;
    this.accountDeploymentData = accountDeploymentData;
    this.nonceDataAvailabilityMode = nonceDataAvailabilityMode;
    this.feeDataAvailabilityMode = feeDataAvailabilityMode;
  }
}
