// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";

export class DeployAccountTransactionV1 {
  static encode(message: DeployAccountTransactionV1, writer: Writer): void {
    writer.uint32(10);
    writer.bytes(message.maxFee);

    writer.uint32(18);
    writer.string(message.version);

    const signature = message.signature;
    if (signature.length !== 0) {
      for (let i: i32 = 0; i < signature.length; ++i) {
        writer.uint32(26);
        writer.bytes(signature[i]);
      }
    }

    writer.uint32(34);
    writer.bytes(message.nonce);

    writer.uint32(42);
    writer.bytes(message.classHash);

    writer.uint32(50);
    writer.bytes(message.contractAddressSalt);

    const constructorCalldata = message.constructorCalldata;
    if (constructorCalldata.length !== 0) {
      for (let i: i32 = 0; i < constructorCalldata.length; ++i) {
        writer.uint32(58);
        writer.bytes(constructorCalldata[i]);
      }
    }
  }

  static decode(reader: Reader, length: i32): DeployAccountTransactionV1 {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new DeployAccountTransactionV1();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.maxFee = reader.bytes();
          break;

        case 2:
          message.version = reader.string();
          break;

        case 3:
          message.signature.push(reader.bytes());
          break;

        case 4:
          message.nonce = reader.bytes();
          break;

        case 5:
          message.classHash = reader.bytes();
          break;

        case 6:
          message.contractAddressSalt = reader.bytes();
          break;

        case 7:
          message.constructorCalldata.push(reader.bytes());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  maxFee: Uint8Array;
  version: string;
  signature: Array<Uint8Array>;
  nonce: Uint8Array;
  classHash: Uint8Array;
  contractAddressSalt: Uint8Array;
  constructorCalldata: Array<Uint8Array>;

  constructor(
    maxFee: Uint8Array = new Uint8Array(0),
    version: string = "",
    signature: Array<Uint8Array> = [],
    nonce: Uint8Array = new Uint8Array(0),
    classHash: Uint8Array = new Uint8Array(0),
    contractAddressSalt: Uint8Array = new Uint8Array(0),
    constructorCalldata: Array<Uint8Array> = []
  ) {
    this.maxFee = maxFee;
    this.version = version;
    this.signature = signature;
    this.nonce = nonce;
    this.classHash = classHash;
    this.contractAddressSalt = contractAddressSalt;
    this.constructorCalldata = constructorCalldata;
  }
}
