// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";

export class DeployTransactionV0 {
  static encode(message: DeployTransactionV0, writer: Writer): void {
    writer.uint32(10);
    writer.bytes(message.classHash);

    writer.uint32(18);
    writer.string(message.version);

    writer.uint32(26);
    writer.bytes(message.contractAddressSalt);

    const constructorCalldata = message.constructorCalldata;
    if (constructorCalldata.length !== 0) {
      for (let i: i32 = 0; i < constructorCalldata.length; ++i) {
        writer.uint32(34);
        writer.bytes(constructorCalldata[i]);
      }
    }
  }

  static decode(reader: Reader, length: i32): DeployTransactionV0 {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new DeployTransactionV0();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.classHash = reader.bytes();
          break;

        case 2:
          message.version = reader.string();
          break;

        case 3:
          message.contractAddressSalt = reader.bytes();
          break;

        case 4:
          message.constructorCalldata.push(reader.bytes());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  classHash: Uint8Array;
  version: string;
  contractAddressSalt: Uint8Array;
  constructorCalldata: Array<Uint8Array>;

  constructor(
    classHash: Uint8Array = new Uint8Array(0),
    version: string = "",
    contractAddressSalt: Uint8Array = new Uint8Array(0),
    constructorCalldata: Array<Uint8Array> = []
  ) {
    this.classHash = classHash;
    this.version = version;
    this.contractAddressSalt = contractAddressSalt;
    this.constructorCalldata = constructorCalldata;
  }
}
