// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";

export class Event {
  static encode(message: Event, writer: Writer): void {
    writer.uint32(10);
    writer.bytes(message.fromAddress);

    const keys = message.keys;
    if (keys.length !== 0) {
      for (let i: i32 = 0; i < keys.length; ++i) {
        writer.uint32(18);
        writer.bytes(keys[i]);
      }
    }

    const data = message.data;
    if (data.length !== 0) {
      for (let i: i32 = 0; i < data.length; ++i) {
        writer.uint32(26);
        writer.bytes(data[i]);
      }
    }
  }

  static decode(reader: Reader, length: i32): Event {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Event();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.fromAddress = reader.bytes();
          break;

        case 2:
          message.keys.push(reader.bytes());
          break;

        case 3:
          message.data.push(reader.bytes());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  fromAddress: Uint8Array;
  keys: Array<Uint8Array>;
  data: Array<Uint8Array>;

  constructor(
    fromAddress: Uint8Array = new Uint8Array(0),
    keys: Array<Uint8Array> = [],
    data: Array<Uint8Array> = []
  ) {
    this.fromAddress = fromAddress;
    this.keys = keys;
    this.data = data;
  }
}
