// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

export enum EXECUTION_STATUS {
  EXECUTION_STATUS_UNKNOWN = 0,
  EXECUTION_STATUS_SUCCESS = 1,
  EXECUTION_STATUS_REVERTED = 2,
}
