// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";
import { DataAvailability } from "./DataAvailability";

export class ExecutionResources {
  static encode(message: ExecutionResources, writer: Writer): void {
    writer.uint32(8);
    writer.uint64(message.steps);

    writer.uint32(16);
    writer.uint64(message.memoryHoles);

    writer.uint32(24);
    writer.uint64(message.rangeCheckBuiltinApplications);

    writer.uint32(32);
    writer.uint64(message.pedersenBuiltinApplications);

    writer.uint32(40);
    writer.uint64(message.poseidonBuiltinApplications);

    writer.uint32(48);
    writer.uint64(message.ecOpBuiltinApplications);

    writer.uint32(56);
    writer.uint64(message.ecdsaBuiltinApplications);

    writer.uint32(64);
    writer.uint64(message.bitwiseBuiltinApplications);

    writer.uint32(72);
    writer.uint64(message.keccakBuiltinApplications);

    writer.uint32(80);
    writer.uint64(message.segmentArenaBuiltin);

    const dataAvailability = message.dataAvailability;
    if (dataAvailability !== null) {
      writer.uint32(90);
      writer.fork();
      DataAvailability.encode(dataAvailability, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): ExecutionResources {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ExecutionResources();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.steps = reader.uint64();
          break;

        case 2:
          message.memoryHoles = reader.uint64();
          break;

        case 3:
          message.rangeCheckBuiltinApplications = reader.uint64();
          break;

        case 4:
          message.pedersenBuiltinApplications = reader.uint64();
          break;

        case 5:
          message.poseidonBuiltinApplications = reader.uint64();
          break;

        case 6:
          message.ecOpBuiltinApplications = reader.uint64();
          break;

        case 7:
          message.ecdsaBuiltinApplications = reader.uint64();
          break;

        case 8:
          message.bitwiseBuiltinApplications = reader.uint64();
          break;

        case 9:
          message.keccakBuiltinApplications = reader.uint64();
          break;

        case 10:
          message.segmentArenaBuiltin = reader.uint64();
          break;

        case 11:
          message.dataAvailability = DataAvailability.decode(
            reader,
            reader.uint32()
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  steps: u64;
  memoryHoles: u64;
  rangeCheckBuiltinApplications: u64;
  pedersenBuiltinApplications: u64;
  poseidonBuiltinApplications: u64;
  ecOpBuiltinApplications: u64;
  ecdsaBuiltinApplications: u64;
  bitwiseBuiltinApplications: u64;
  keccakBuiltinApplications: u64;
  segmentArenaBuiltin: u64;
  dataAvailability: DataAvailability | null;

  constructor(
    steps: u64 = 0,
    memoryHoles: u64 = 0,
    rangeCheckBuiltinApplications: u64 = 0,
    pedersenBuiltinApplications: u64 = 0,
    poseidonBuiltinApplications: u64 = 0,
    ecOpBuiltinApplications: u64 = 0,
    ecdsaBuiltinApplications: u64 = 0,
    bitwiseBuiltinApplications: u64 = 0,
    keccakBuiltinApplications: u64 = 0,
    segmentArenaBuiltin: u64 = 0,
    dataAvailability: DataAvailability | null = null
  ) {
    this.steps = steps;
    this.memoryHoles = memoryHoles;
    this.rangeCheckBuiltinApplications = rangeCheckBuiltinApplications;
    this.pedersenBuiltinApplications = pedersenBuiltinApplications;
    this.poseidonBuiltinApplications = poseidonBuiltinApplications;
    this.ecOpBuiltinApplications = ecOpBuiltinApplications;
    this.ecdsaBuiltinApplications = ecdsaBuiltinApplications;
    this.bitwiseBuiltinApplications = bitwiseBuiltinApplications;
    this.keccakBuiltinApplications = keccakBuiltinApplications;
    this.segmentArenaBuiltin = segmentArenaBuiltin;
    this.dataAvailability = dataAvailability;
  }
}
