// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";

export class InvokeTransactionV0 {
  static encode(message: InvokeTransactionV0, writer: Writer): void {
    writer.uint32(18);
    writer.bytes(message.maxFee);

    writer.uint32(26);
    writer.string(message.version);

    const signature = message.signature;
    if (signature.length !== 0) {
      for (let i: i32 = 0; i < signature.length; ++i) {
        writer.uint32(34);
        writer.bytes(signature[i]);
      }
    }

    writer.uint32(42);
    writer.bytes(message.contractAddress);

    writer.uint32(50);
    writer.bytes(message.entryPointSelector);

    const calldata = message.calldata;
    if (calldata.length !== 0) {
      for (let i: i32 = 0; i < calldata.length; ++i) {
        writer.uint32(58);
        writer.bytes(calldata[i]);
      }
    }
  }

  static decode(reader: Reader, length: i32): InvokeTransactionV0 {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new InvokeTransactionV0();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2:
          message.maxFee = reader.bytes();
          break;

        case 3:
          message.version = reader.string();
          break;

        case 4:
          message.signature.push(reader.bytes());
          break;

        case 5:
          message.contractAddress = reader.bytes();
          break;

        case 6:
          message.entryPointSelector = reader.bytes();
          break;

        case 7:
          message.calldata.push(reader.bytes());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  maxFee: Uint8Array;
  version: string;
  signature: Array<Uint8Array>;
  contractAddress: Uint8Array;
  entryPointSelector: Uint8Array;
  calldata: Array<Uint8Array>;

  constructor(
    maxFee: Uint8Array = new Uint8Array(0),
    version: string = "",
    signature: Array<Uint8Array> = [],
    contractAddress: Uint8Array = new Uint8Array(0),
    entryPointSelector: Uint8Array = new Uint8Array(0),
    calldata: Array<Uint8Array> = []
  ) {
    this.maxFee = maxFee;
    this.version = version;
    this.signature = signature;
    this.contractAddress = contractAddress;
    this.entryPointSelector = entryPointSelector;
    this.calldata = calldata;
  }
}
