// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";

export class L1HandlerTransaction {
  static encode(message: L1HandlerTransaction, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.version);

    writer.uint32(26);
    writer.string(message.nonce);

    writer.uint32(34);
    writer.bytes(message.contractAddress);

    writer.uint32(42);
    writer.bytes(message.entryPointSelector);

    const calldata = message.calldata;
    if (calldata.length !== 0) {
      for (let i: i32 = 0; i < calldata.length; ++i) {
        writer.uint32(50);
        writer.bytes(calldata[i]);
      }
    }
  }

  static decode(reader: Reader, length: i32): L1HandlerTransaction {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new L1HandlerTransaction();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.version = reader.string();
          break;

        case 3:
          message.nonce = reader.string();
          break;

        case 4:
          message.contractAddress = reader.bytes();
          break;

        case 5:
          message.entryPointSelector = reader.bytes();
          break;

        case 6:
          message.calldata.push(reader.bytes());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  version: string;
  nonce: string;
  contractAddress: Uint8Array;
  entryPointSelector: Uint8Array;
  calldata: Array<Uint8Array>;

  constructor(
    version: string = "",
    nonce: string = "",
    contractAddress: Uint8Array = new Uint8Array(0),
    entryPointSelector: Uint8Array = new Uint8Array(0),
    calldata: Array<Uint8Array> = []
  ) {
    this.version = version;
    this.nonce = nonce;
    this.contractAddress = contractAddress;
    this.entryPointSelector = entryPointSelector;
    this.calldata = calldata;
  }
}
