// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";

export class MessagesSent {
  static encode(message: MessagesSent, writer: Writer): void {
    writer.uint32(10);
    writer.bytes(message.fromAddress);

    writer.uint32(18);
    writer.bytes(message.toAddress);

    const payload = message.payload;
    if (payload.length !== 0) {
      for (let i: i32 = 0; i < payload.length; ++i) {
        writer.uint32(26);
        writer.bytes(payload[i]);
      }
    }
  }

  static decode(reader: Reader, length: i32): MessagesSent {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MessagesSent();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.fromAddress = reader.bytes();
          break;

        case 2:
          message.toAddress = reader.bytes();
          break;

        case 3:
          message.payload.push(reader.bytes());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  fromAddress: Uint8Array;
  toAddress: Uint8Array;
  payload: Array<Uint8Array>;

  constructor(
    fromAddress: Uint8Array = new Uint8Array(0),
    toAddress: Uint8Array = new Uint8Array(0),
    payload: Array<Uint8Array> = []
  ) {
    this.fromAddress = fromAddress;
    this.toAddress = toAddress;
    this.payload = payload;
  }
}
