// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";

export class Resource {
  static encode(message: Resource, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.maxAmount);

    writer.uint32(18);
    writer.string(message.maxPricePerUnit);
  }

  static decode(reader: Reader, length: i32): Resource {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Resource();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.maxAmount = reader.string();
          break;

        case 2:
          message.maxPricePerUnit = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  maxAmount: string;
  maxPricePerUnit: string;

  constructor(maxAmount: string = "", maxPricePerUnit: string = "") {
    this.maxAmount = maxAmount;
    this.maxPricePerUnit = maxPricePerUnit;
  }
}
