// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";
import { Resource } from "./Resource";

export class ResourceBounds {
  static encode(message: ResourceBounds, writer: Writer): void {
    const l1Gas = message.l1Gas;
    if (l1Gas !== null) {
      writer.uint32(10);
      writer.fork();
      Resource.encode(l1Gas, writer);
      writer.ldelim();
    }

    const l2Gas = message.l2Gas;
    if (l2Gas !== null) {
      writer.uint32(18);
      writer.fork();
      Resource.encode(l2Gas, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): ResourceBounds {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ResourceBounds();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.l1Gas = Resource.decode(reader, reader.uint32());
          break;

        case 2:
          message.l2Gas = Resource.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  l1Gas: Resource | null;
  l2Gas: Resource | null;

  constructor(l1Gas: Resource | null = null, l2Gas: Resource | null = null) {
    this.l1Gas = l1Gas;
    this.l2Gas = l2Gas;
  }
}
