// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";
import { InvokeTransactionV0 } from "./InvokeTransactionV0";
import { InvokeTransactionV1 } from "./InvokeTransactionV1";
import { InvokeTransactionV3 } from "./InvokeTransactionV3";
import { L1HandlerTransaction } from "./L1HandlerTransaction";
import { DeclareTransactionV0 } from "./DeclareTransactionV0";
import { DeclareTransactionV1 } from "./DeclareTransactionV1";
import { DeclareTransactionV2 } from "./DeclareTransactionV2";
import { DeclareTransactionV3 } from "./DeclareTransactionV3";
import { DeployTransactionV0 } from "./DeployTransactionV0";
import { DeployAccountTransactionV1 } from "./DeployAccountTransactionV1";
import { DeployAccountTransactionV3 } from "./DeployAccountTransactionV3";
import { TransactionReceipt } from "./TransactionReceipt";

export class TransactionWithReceipt {
  static encode(message: TransactionWithReceipt, writer: Writer): void {
    const invokeTransactionV0 = message.invokeTransactionV0;
    if (invokeTransactionV0 !== null) {
      writer.uint32(10);
      writer.fork();
      InvokeTransactionV0.encode(invokeTransactionV0, writer);
      writer.ldelim();
    }

    const invokeTransactionV1 = message.invokeTransactionV1;
    if (invokeTransactionV1 !== null) {
      writer.uint32(18);
      writer.fork();
      InvokeTransactionV1.encode(invokeTransactionV1, writer);
      writer.ldelim();
    }

    const invokeTransactionV3 = message.invokeTransactionV3;
    if (invokeTransactionV3 !== null) {
      writer.uint32(26);
      writer.fork();
      InvokeTransactionV3.encode(invokeTransactionV3, writer);
      writer.ldelim();
    }

    const l1HandlerTransaction = message.l1HandlerTransaction;
    if (l1HandlerTransaction !== null) {
      writer.uint32(34);
      writer.fork();
      L1HandlerTransaction.encode(l1HandlerTransaction, writer);
      writer.ldelim();
    }

    const declareTransactionV0 = message.declareTransactionV0;
    if (declareTransactionV0 !== null) {
      writer.uint32(42);
      writer.fork();
      DeclareTransactionV0.encode(declareTransactionV0, writer);
      writer.ldelim();
    }

    const declareTransactionV1 = message.declareTransactionV1;
    if (declareTransactionV1 !== null) {
      writer.uint32(50);
      writer.fork();
      DeclareTransactionV1.encode(declareTransactionV1, writer);
      writer.ldelim();
    }

    const declareTransactionV2 = message.declareTransactionV2;
    if (declareTransactionV2 !== null) {
      writer.uint32(58);
      writer.fork();
      DeclareTransactionV2.encode(declareTransactionV2, writer);
      writer.ldelim();
    }

    const declareTransactionV3 = message.declareTransactionV3;
    if (declareTransactionV3 !== null) {
      writer.uint32(66);
      writer.fork();
      DeclareTransactionV3.encode(declareTransactionV3, writer);
      writer.ldelim();
    }

    const deployTransactionV0 = message.deployTransactionV0;
    if (deployTransactionV0 !== null) {
      writer.uint32(74);
      writer.fork();
      DeployTransactionV0.encode(deployTransactionV0, writer);
      writer.ldelim();
    }

    const deployAccountTransactionV1 = message.deployAccountTransactionV1;
    if (deployAccountTransactionV1 !== null) {
      writer.uint32(82);
      writer.fork();
      DeployAccountTransactionV1.encode(deployAccountTransactionV1, writer);
      writer.ldelim();
    }

    const deployAccountTransactionV3 = message.deployAccountTransactionV3;
    if (deployAccountTransactionV3 !== null) {
      writer.uint32(90);
      writer.fork();
      DeployAccountTransactionV3.encode(deployAccountTransactionV3, writer);
      writer.ldelim();
    }

    const receipt = message.receipt;
    if (receipt !== null) {
      writer.uint32(98);
      writer.fork();
      TransactionReceipt.encode(receipt, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): TransactionWithReceipt {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new TransactionWithReceipt();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.invokeTransactionV0 = InvokeTransactionV0.decode(
            reader,
            reader.uint32()
          );
          break;

        case 2:
          message.invokeTransactionV1 = InvokeTransactionV1.decode(
            reader,
            reader.uint32()
          );
          break;

        case 3:
          message.invokeTransactionV3 = InvokeTransactionV3.decode(
            reader,
            reader.uint32()
          );
          break;

        case 4:
          message.l1HandlerTransaction = L1HandlerTransaction.decode(
            reader,
            reader.uint32()
          );
          break;

        case 5:
          message.declareTransactionV0 = DeclareTransactionV0.decode(
            reader,
            reader.uint32()
          );
          break;

        case 6:
          message.declareTransactionV1 = DeclareTransactionV1.decode(
            reader,
            reader.uint32()
          );
          break;

        case 7:
          message.declareTransactionV2 = DeclareTransactionV2.decode(
            reader,
            reader.uint32()
          );
          break;

        case 8:
          message.declareTransactionV3 = DeclareTransactionV3.decode(
            reader,
            reader.uint32()
          );
          break;

        case 9:
          message.deployTransactionV0 = DeployTransactionV0.decode(
            reader,
            reader.uint32()
          );
          break;

        case 10:
          message.deployAccountTransactionV1 =
            DeployAccountTransactionV1.decode(reader, reader.uint32());
          break;

        case 11:
          message.deployAccountTransactionV3 =
            DeployAccountTransactionV3.decode(reader, reader.uint32());
          break;

        case 12:
          message.receipt = TransactionReceipt.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  invokeTransactionV0: InvokeTransactionV0 | null;
  invokeTransactionV1: InvokeTransactionV1 | null;
  invokeTransactionV3: InvokeTransactionV3 | null;
  l1HandlerTransaction: L1HandlerTransaction | null;
  declareTransactionV0: DeclareTransactionV0 | null;
  declareTransactionV1: DeclareTransactionV1 | null;
  declareTransactionV2: DeclareTransactionV2 | null;
  declareTransactionV3: DeclareTransactionV3 | null;
  deployTransactionV0: DeployTransactionV0 | null;
  deployAccountTransactionV1: DeployAccountTransactionV1 | null;
  deployAccountTransactionV3: DeployAccountTransactionV3 | null;
  receipt: TransactionReceipt | null;

  constructor(
    invokeTransactionV0: InvokeTransactionV0 | null = null,
    invokeTransactionV1: InvokeTransactionV1 | null = null,
    invokeTransactionV3: InvokeTransactionV3 | null = null,
    l1HandlerTransaction: L1HandlerTransaction | null = null,
    declareTransactionV0: DeclareTransactionV0 | null = null,
    declareTransactionV1: DeclareTransactionV1 | null = null,
    declareTransactionV2: DeclareTransactionV2 | null = null,
    declareTransactionV3: DeclareTransactionV3 | null = null,
    deployTransactionV0: DeployTransactionV0 | null = null,
    deployAccountTransactionV1: DeployAccountTransactionV1 | null = null,
    deployAccountTransactionV3: DeployAccountTransactionV3 | null = null,
    receipt: TransactionReceipt | null = null
  ) {
    this.invokeTransactionV0 = invokeTransactionV0;
    this.invokeTransactionV1 = invokeTransactionV1;
    this.invokeTransactionV3 = invokeTransactionV3;
    this.l1HandlerTransaction = l1HandlerTransaction;
    this.declareTransactionV0 = declareTransactionV0;
    this.declareTransactionV1 = declareTransactionV1;
    this.declareTransactionV2 = declareTransactionV2;
    this.declareTransactionV3 = declareTransactionV3;
    this.deployTransactionV0 = deployTransactionV0;
    this.deployAccountTransactionV1 = deployAccountTransactionV1;
    this.deployAccountTransactionV3 = deployAccountTransactionV3;
    this.receipt = receipt;
  }
}
