// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";
import { ActualFee } from "./ActualFee";
import { MessagesSent } from "./MessagesSent";
import { Event } from "./Event";
import { ExecutionResources } from "./ExecutionResources";
import { EXECUTION_STATUS } from "./EXECUTION_STATUS";
import { TRANSACTION_TYPE } from "./TRANSACTION_TYPE";

export class TransactionReceipt {
  static encode(message: TransactionReceipt, writer: Writer): void {
    writer.uint32(10);
    writer.bytes(message.transactionHash);

    const actualFee = message.actualFee;
    if (actualFee !== null) {
      writer.uint32(18);
      writer.fork();
      ActualFee.encode(actualFee, writer);
      writer.ldelim();
    }

    writer.uint32(24);
    writer.int32(message.executionStatus);

    writer.uint32(34);
    writer.string(message.revertReason);

    writer.uint32(40);
    writer.int32(message.type);

    writer.uint32(50);
    writer.string(message.messageHash);

    const messagesSent = message.messagesSent;
    for (let i: i32 = 0; i < messagesSent.length; ++i) {
      writer.uint32(58);
      writer.fork();
      MessagesSent.encode(messagesSent[i], writer);
      writer.ldelim();
    }

    const events = message.events;
    for (let i: i32 = 0; i < events.length; ++i) {
      writer.uint32(66);
      writer.fork();
      Event.encode(events[i], writer);
      writer.ldelim();
    }

    const executionResources = message.executionResources;
    if (executionResources !== null) {
      writer.uint32(74);
      writer.fork();
      ExecutionResources.encode(executionResources, writer);
      writer.ldelim();
    }

    writer.uint32(82);
    writer.bytes(message.contractAddress);
  }

  static decode(reader: Reader, length: i32): TransactionReceipt {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new TransactionReceipt();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.transactionHash = reader.bytes();
          break;

        case 2:
          message.actualFee = ActualFee.decode(reader, reader.uint32());
          break;

        case 3:
          message.executionStatus = reader.int32();
          break;

        case 4:
          message.revertReason = reader.string();
          break;

        case 5:
          message.type = reader.int32();
          break;

        case 6:
          message.messageHash = reader.string();
          break;

        case 7:
          message.messagesSent.push(
            MessagesSent.decode(reader, reader.uint32())
          );
          break;

        case 8:
          message.events.push(Event.decode(reader, reader.uint32()));
          break;

        case 9:
          message.executionResources = ExecutionResources.decode(
            reader,
            reader.uint32()
          );
          break;

        case 10:
          message.contractAddress = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  transactionHash: Uint8Array;
  actualFee: ActualFee | null;
  executionStatus: EXECUTION_STATUS;
  revertReason: string;
  type: TRANSACTION_TYPE;
  messageHash: string;
  messagesSent: Array<MessagesSent>;
  events: Array<Event>;
  executionResources: ExecutionResources | null;
  contractAddress: Uint8Array;

  constructor(
    transactionHash: Uint8Array = new Uint8Array(0),
    actualFee: ActualFee | null = null,
    executionStatus: EXECUTION_STATUS = 0,
    revertReason: string = "",
    type: TRANSACTION_TYPE = 0,
    messageHash: string = "",
    messagesSent: Array<MessagesSent> = [],
    events: Array<Event> = [],
    executionResources: ExecutionResources | null = null,
    contractAddress: Uint8Array = new Uint8Array(0)
  ) {
    this.transactionHash = transactionHash;
    this.actualFee = actualFee;
    this.executionStatus = executionStatus;
    this.revertReason = revertReason;
    this.type = type;
    this.messageHash = messageHash;
    this.messagesSent = messagesSent;
    this.events = events;
    this.executionResources = executionResources;
    this.contractAddress = contractAddress;
  }
}
