// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

export enum TRANSACTION_TYPE {
  TRANSACTION_TYPE_UNKNOWN = 0,
  INVOKE = 1,
  DECLARE = 2,
  DEPLOY = 3,
  DEPLOY_ACCOUNT = 4,
  L1_HANDLER = 5,
}
